### ISSUE TITLE
Does not work with simple collections

### ISSUE THREAD

**Issue by nemcek** [graphile-contrib/pg-omit-archived#1]
When using Postgraphile as a library and passing `simpleCollections: 'only'`, the argument `includeArchived` is not generated in schema and also there is no `is_archived` column anywhere in the generated sql.

**Comment by benjie** [comment]
You're right; there's a check that it's a (Relay) connection here:

https://github.com/graphile-contrib/pg-omit-archived/blob/76e2271f2769edab0da2c22983c18692a1a78d9a/index.js#L75

You might try loosening that constraint:

```js
    !(isPgFieldConnection || isPgFieldSimpleCollection) ||
```

And seeing what happens. Happy to review a PR with tests 👍

**Comment by benjie** [comment]
Released in v2.1.0
