### ISSUE TITLE
Ability to use a timestamp 

### ISSUE THREAD

**Issue by testarossaaaaa** [graphile-contrib/pg-omit-archived#2]
Is it possible to use a nullable timestamp like `deleted_at` to implement a soft deletion as is customary in other frameworks? Sometimes it is useful to know when the removal occurred. In our case, we keep records of actions in the system, and the fact of deletion could be easily recorded along with the time.

**Comment by benjie** [comment]
Yes, this should already work, just pass the timestamp column instead of the boolean column.
