### ISSUE TITLE
Ability to use expression to omit rows

### ISSUE THREAD

**Issue by renatko** [graphile-contrib/pg-omit-archived#25]
We have text column `status` and we would like to omit rows with certain value(s). 

The idea is to allow to configure the plugin with kind of expression (eg `status != 'deleted'`). As we already have discussed, the syntax could be like:
```
pgStatusDeletedAppliesTo: ['app_public.my_table', 'app_public.my_other_table'],
pgStatusDeletedExpression: (sql, tableAlias) => sql.fragment`${tableAlias}.status != 'deleted'`,
```

**Comment by benjie** [comment]
Released in @graphile-contrib/pg-omit-archived@3.0.0-rc.8 :raised_hands:
