### ISSUE TITLE
Any estimate for the 3.0 GA release date?

### ISSUE THREAD

**Issue by bajtos** [graphile-contrib/pg-omit-archived#31]
First of all, thank you for this great Postgraphile plugin ❤️ I appreciate all the effort you are putting into maintaining and improving this package.

In my project, I would like to use the recently added "advanced expressions" mode, which is available in v3.0.0 relase candidates only. (I am interested in TypeScript typings too, but those can be easily supplied by a `.d.ts` file.)

The `Releases` page shows that the last 3.0 release candidate was published back in August 2021.

What is your plan for 3.0 GA? Are there any features or bugfixes missing? How can we (the community of users) help the project to reach 3.0 GA sooner?

**Comment by benjie** [comment]
Go ahead and use it; it’s fine as is 👍 (I’ve been using it in production since August.) I’ll put doing a new release on my todo list but it’ll be the same code just a different version number (also I’m focussed on V5 at the moment so it might take me a while to get around to).

**Comment by benjie** [comment]
v3 released :tada:

**Comment by bajtos** [comment]
Perfect, thank you! 🙇🏻‍♂️
