### ISSUE TITLE
Option 'appendPlugins' should be an array of functions, found 'object'

### ISSUE THREAD

**Issue by agad** [graphile-contrib/pg-omit-archived#37]
When importing the plugin as a module and including it in the array for appendPlugins, I receive the following error:

`Option 'appendPlugins' should be an array of functions, found 'object' at index 0","stack":"Error: Option 'appendPlugins' should be an array of functions, found 'object' at index 0\n    at ensureValidPlugins (/usr/src/app/node_modules/postgraphile-core/node8plus/index.js:18:19)\n    at getPostGraphileBuilder (/usr/src/app/node_modules/postgraphile-core/node8plus/index.js:169:5)\n    at createPostGraphileSchema (/usr/src/app/node_modules/postgraphile-core/node8plus/index.js:224:62)\n`

I am importing as follows:

`import PgOmitArchived from '@graphile-contrib/pg-omit-archived' `

Using version  ^3.2.1

Works fine when its just required instead of imported as module.

**Comment by benjie** [comment]
Try PgOmitArchived.default

**Comment by agad** [comment]
Perfect, thanks!
